# gepro/script_generator.py
from typing import Dict, Any

def generate_python_script(workflow: Dict[str, Any]) -> str:
    """
    Converts a workflow dictionary into a standalone Python script.
    """
    script_lines = [
        "import geopandas as gpd",
        "import os",
        "import subprocess",
        "",
        "# Generated by gepro Script Generator",
        "context = {}",
        ""
    ]

    for i, step in enumerate(workflow.get('steps', [])):
        tool = step.get('tool')
        cmd = step.get('command')
        params = step.get('params', {})
        out = step.get('output')

        script_lines.append(f"# Step {i+1}: {tool}.{cmd}")
        
        if tool == 'geopandas':
            if cmd == 'read_file':
                script_lines.append(f"context['{out}'] = gpd.read_file(\"{params.get('filepath')}\")")
            elif cmd == 'to_crs':
                script_lines.append(f"context['{out}'] = context['{params.get('gdf')}'].to_crs(\"{params.get('crs')}\")")
            # ... can add more specialized translations here
        
        elif tool == 'gdal':
            script_lines.append(f"# GDAL task: {' '.join(params.get('options', []))} {params.get('input')} {params.get('output')}")
            # Simplified subprocess call
            script_lines.append(f"subprocess.run(['gdal_{cmd}', ...])")

        script_lines.append("")

    return "\n".join(script_lines)
